data:
  path: "data/raw"
  market_data_file: "market_data.csv"

model:
  type: "random_forest"
  n_estimators: 100
  max_depth: 10

features:
  technical_indicators:
    - MA
    - RSI
    - MACD

backtest:
  initial_capital: 100000
  position_size: 0.1
  stop_loss: 0.02
  take_profit: 0.05 